### ISSUE TITLE
(kMeans, cosine) wrong number of centroids (?)

### ISSUE THREAD

**Issue by galkowskit** [Yomguithereal/talisman#103] opened 2017-02-14 12:53 UTC
I'm trying to cluster sentences using TF-IDF, cosine similarity and k-means algorithm. I calculate TF-IDF using `natural` library then I prepare vectors that look like:

`[0, 0, 0, 0, 0, 1.24225242, 0, 0, 0, 0, 0]` where every value represents a word and the whole vector represents a sentence (in case of this example it would be a sentence with one word).

Then I try to use `talisman` library to make clusters using created vectors and `metrics/distance/cosine`. The problem is that I get:

```
TypeError: Cannot read property 'length' of undefined
    at KMeans.cosine [as distance] (.../node_modules/talisman/metrics/distance/cosine.js:29:21)
    at KMeans.iterate (.../node_modules/talisman/clustering/k-means.js:164:22)
    at KMeans.run (.../node_modules/talisman/clustering/k-means.js:224:12)
    at kMeans (.../node_modules/talisman/clustering/k-means.js:243:21)
    at Object.<anonymous> (.../lev-kmeans.js:39:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

I tried looking into the code and the reason it fails is this piece of code (https://github.com/Yomguithereal/talisman/blob/master/src/clustering/k-means.js#L148).

```
for (let j = 0, m = this.dimensions; j < m; j++) {
     const d = this.distance(vector, this.centroids[j]);

     if (d < min) {
         min = d;
         minIndex = j;
     }
}
```

It tries to enter `cosine.js` functions using `undefined` as the second vector. For example for `k` equal 2 it should generate 2 centroids. It does. But this loop is trying to access centroids with very high indices like 181 (`this.dimensions` and thus `m` is equal 182).

It works fine when I tested it for simpler stuff using Euclidean distances.

To be complete I add the way I initialize the `kMeans`:

```
const clusters = kMeans({
    distance: cosine,
    k: 6,
}, vectors)
```

Where `cosine` is a `const cosine = require('talisman/metrics/distance/cosine')`.

**Comment by Yomguithereal** [comment] 2017-02-14 13:05
Hello @galkowskit. I guess you're right. `m` should probably be `this.k` no? It's really weird that my tests passed. Vector dimensions should be equal to k in my tests...

On a side note, I have a little undocumented helper to build tf/idf vectors from documents if you ever need it.

**Comment by Yomguithereal** [comment] 2017-02-14 13:15
Just published a v0.18.0 with a fix. Can you tell me whether this fix your issue please?

Out of curiosity, what are you trying to cluster?

**Comment by galkowskit** [comment] 2017-02-14 13:21
I will test it in a moment, but when I applied the changes from 5ea30a753d7f2fc7cee46e0f88e3b5cb06e9bb04 it seems to fail from time to time on generating new centroids.

I'm trying to cluster around 1000 strings based on similar keywords.

**Comment by Yomguithereal** [comment] 2017-02-14 13:26
>  it seems to fail from time to time on generating new centroids.

What do you mean? Is an Error thrown? Is there a syntax error?

**Comment by galkowskit** [comment] 2017-02-14 13:28
Yes, when I try to cluster those using v0.18.0 the problem I described above is still present. It works in `k-means.js` but fails from time to time (not always, so it might be a bug with randomizing centroids) on `helpers/vectors.js`.

```
TypeError: Cannot read property 'length' of undefined
    at mean (.../node_modules/talisman/helpers/vectors.js:77:27)
    at KMeans.iterate (.../node_modules/talisman/clustering/k-means.js:201:47)
    at KMeans.run (.../node_modules/talisman/clustering/k-means.js:221:12)
    at kMeans (.../node_modules/talisman/clustering/k-means.js:240:21)
    at Object.<anonymous> (.../lev-kmeans.js:39:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by Yomguithereal** [comment] 2017-02-14 13:37
Can I ask you for your data and your `k` to be able to reproduce and fix? It seems to be an issue with empty centroids and the fact we have to pluck random vectors to populate them.

**Comment by Yomguithereal** [comment] 2017-02-14 13:45
On a side note: this is the undocumented function I was speaking about [here](https://github.com/Yomguithereal/talisman/blob/master/src/features/extraction/vectorizers.js#L212-L278).

**Comment by galkowskit** [comment] 2017-02-14 13:54
https://github.com/galkowskit/talisman-issue-103

I created a small repository with the data and the code I am using to cluster things. You can reproduce the problems by `npm install` and then `npm start` a few times. It randomly fails.

The `data.js` contains raw input data (one that I am expecting) and then in `index.js` I transform it to vectors and start clustering. Hope it helps.

(And thanks for the function I will give it a try!)

**Comment by Yomguithereal** [comment] 2017-02-15 10:51
Thanks @galkowskit. I should be able to find some time this afternoon to fix this issue (I will also mostly rewrite the clusterer's code because it can be more efficient).

**Comment by Yomguithereal** [comment] 2017-02-15 13:53
Ok @galkowskit. I just committed a fix (plus a performance rewrite). Can you test the code and tell me if we're reaching a finally correct implementation so I can release a new version on npm please?

**Comment by galkowskit** [comment] 2017-02-15 14:16
I have tested the version on the `master` branch and it seems to be working fine on the data I gave you. Out of twenty times I ran it, it didn't crash even once. So I believe the problem with randomized centroids is solved. Thanks a lot!

I still need to figure out some things about my own implementation (I might have some errors in the way I generate results) but it's out of the scope of this issue and the bug seems to be solved. :)

**Comment by Yomguithereal** [comment] 2017-02-15 14:28
I also did similar tests on my end (with cosine similarity etc.) and find it painful to require a `Map` to trace back to the original docs etc. I think I will add an option named `vector` that is a function returning the vector on which to work in a collection. So you can work with something like this for instance:

```js
[
  {data: 'whatever', vector: [...]},
  ...
]

kMeans({..., vector: item => item.vector}, data);
```

My other (undocumented, sigh...) clusterer can work like this by tweaking only the `distance` function used but in this case, since I need to "mean" the vectors, I cannot, hence the `vector` option.

What do you think?

**Comment by Yomguithereal** [comment] 2017-02-15 14:33
On a side note: are you trying to cluster your documents to find fuzzy duplicates? Or is it rather to group them?

**Comment by galkowskit** [comment] 2017-02-15 14:50
I am trying to create groups of documents that are similar/have similar tags on one of their keys (`description`). Currently I'm struggling with the correct approach and can't really get it to work the way it should. I even created a SO question if you/anyone is interested (http://stackoverflow.com/questions/42245050/nlp-bag-of-words-tf-idf-for-clustering-and-classifying-short-sentences) in details.

**Comment by Yomguithereal** [comment] 2017-02-15 14:57
For your n°2, naive bayes classifier really seems to be the way to go. There is one undocumented one in this library but I am not sure it is fitting in your case since it is not the variant that exist to specifically classify text documents.

For n°1, if you just need to cluster, I have some ideas I can try. Will put some ideas in a gist later.

**Comment by Yomguithereal** [comment] 2017-02-15 15:15
Ok so the issue with your data is that the description is quite terse and seems to be consisting of only 3 tokens each time, which is not a lot. Using Jaccard coefficient, I can gather some of your documents together but this is not ideal:

```js
const data = require('./data.js');

const jaccard = require('talisman/metrics/distance/jaccard');
const naiveClusterer = require('talisman/clustering/record-linkage/naive');

const documents = data.map(item => item.description.split(' '));

const clusters = naiveClusterer({
  similarity: (a, b) => jaccard(a, b) >= 0.5
}, documents);

clusters.forEach(cluster => {
  console.log('Found a cluster with ' + cluster.length + ' items:');

  cluster.forEach(doc => {
    console.log('   ' + doc.join(' '));
  });
});
```

Note that all the docs not in a cluster are just not linked to no other doc and that produced clusters are fuzzy (meaning that one doc can be in several clusters).

**Comment by galkowskit** [comment] 2017-02-15 15:23
`description` can be anywhere from 1 to 7-12 words. It's basically a single sentence, maybe two (rarely). What I am aiming at is getting very strict groups that could contain only several elements. Most of the docs could be totally non-clustered.

...which seams to be nearly exactly what happens if I run it with the gist above. 😮

**Comment by Yomguithereal** [comment] 2017-02-15 15:28
Ok, the thing was that in the data you provided in the repo, the `description` key seems to always yield only three tokens.

So are we going in the good direction?

**Comment by galkowskit** [comment] 2017-02-15 16:20
Yes, I haven't even considered using Jaccard but it seems to work perfectly. When I added a tokenizer and some stopwords and used it on some actual data it is working perfectly even on non-English language. The only thing that I miss is getting the ID/index of the original document (to make a lookup for the object itself). Or even passing the whole objects into the clusterer with syntax like:

```
const clusters = naiveClusterer({
  similarity: (a, b) => {
      return jaccard(a.description, b.description) > 0.2
  }
}, data);
```

But that would require too many changes I believe. And would hit the performance.

**Comment by Yomguithereal** [comment] 2017-02-15 16:28
No. This would actually work. I often do that and this really won't hurt performance too much. However, know that this clusterer is called naive for a reason: it works in quadratic time (O(n * (n - 1) / 2) to be precise. So if this is fine for not too much docs, it will start being really slow if you have a lot of docs. But I have other techniques to perform this kind of work in a scalable fashion if you ever have performance issues.

**Comment by Yomguithereal** [comment] 2017-02-15 16:39
And beware, because this method may possibly put a single vector in two separate clusters.

**Comment by galkowskit** [comment] 2017-02-15 17:11
Yes, it does work fine with objects being pushed into the clusterer. It manages to cluster 5000 documents in around 55 seconds.

If you have any other idea for improving performance etc. those will always be welcomed. As for the vectors that happen to be in two clusters - it's not a big issue, I will assign only the first one.

I have one more question though: how would you approach classification of new data into an existing clusters?

eg.
First time the data is clustered it creates some clusters.
Second time new data is clustered it should take existing clusters in consideration (ie. in database) from the first clustering.

After clustering I was thinking about auto-tagging those clusters using TF-IDF.

**Comment by Yomguithereal** [comment] 2017-02-15 17:34
> If you have any other idea for improving performance etc.

I have two ideas that we can try one after the other (the last one might not give us an edge here because we have too few documents). But I'll need some time to write a gist.

> I have one more question though: how would you approach classification of new data into an existing clusters?

I would probably use a naive bayes classifier (I think the one from `natural` is pretty decent for this kind of tasks) using the number of the cluster as label.

Else you can also "summarize" each of the cluster by taking a random document in it and then compare the new document to each of those "fingerprint" documents to see whether it can fit in one. However this will run in a time linear to the number of clusters.

> After clustering I was thinking about auto-tagging those clusters using TF-IDF.

Interesting. Do you mean to keep, for instance, the top n tokens of your document using TF-IDF score?

**Comment by galkowskit** [comment] 2017-02-15 17:41
> Interesting. Do you mean to keep, for instance, the top n tokens of your document using TF-IDF score?
Yes. Basically each cluster would be summarized by top n TF-IDF tokens and those would be saved. Just for auto-tagging. I was thinking that those could also be useful for classification.

**Closed** 2017-03-20 14:06 UTC
Labels: bug
